package com.amor.orm.mapper;

import com.amor.orm.model.ABusinessDict;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ABusinessDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_BUSINESS_DICT
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    @Delete({
        "delete from A_BUSINESS_DICT",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_BUSINESS_DICT
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    @Insert({
        "insert into A_BUSINESS_DICT (id, dict_class, ",
        "dict_key, dict_val, ",
        "create_time, update_time, ",
        "create_uid, update_uid)",
        "values (#{id,jdbcType=INTEGER}, #{dictClass,jdbcType=VARCHAR}, ",
        "#{dictKey,jdbcType=INTEGER}, #{dictVal,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{createUid,jdbcType=INTEGER}, #{updateUid,jdbcType=INTEGER})"
    })
    int insert(ABusinessDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_BUSINESS_DICT
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    @Select({
        "select",
        "id, dict_class, dict_key, dict_val, create_time, update_time, create_uid, update_uid",
        "from A_BUSINESS_DICT",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="dict_class", property="dictClass", jdbcType=JdbcType.VARCHAR),
        @Result(column="dict_key", property="dictKey", jdbcType=JdbcType.INTEGER),
        @Result(column="dict_val", property="dictVal", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_uid", property="createUid", jdbcType=JdbcType.INTEGER),
        @Result(column="update_uid", property="updateUid", jdbcType=JdbcType.INTEGER)
    })
    ABusinessDict selectByPrimaryKey(Integer id);
    
    /**
     * This method selects dictionary key-value pairs by dictionary class.
     * This method corresponds to the database table A_BUSINESS_DICT
     *
     * @author sicong.yang
     */
    @Select({
        "select",
        "id, dict_class, dict_key, dict_val, create_time, update_time, create_uid, update_uid",
        "from A_BUSINESS_DICT",
        "where dict_class = #{dict_class,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="dict_class", property="dictClass", jdbcType=JdbcType.VARCHAR),
        @Result(column="dict_key", property="dictKey", jdbcType=JdbcType.INTEGER),
        @Result(column="dict_val", property="dictVal", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_uid", property="createUid", jdbcType=JdbcType.INTEGER),
        @Result(column="update_uid", property="updateUid", jdbcType=JdbcType.INTEGER)
    })
    List<ABusinessDict> selectByDict(String dict_class);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_BUSINESS_DICT
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    @Select({
        "select",
        "id, dict_class, dict_key, dict_val, create_time, update_time, create_uid, update_uid",
        "from A_BUSINESS_DICT"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="dict_class", property="dictClass", jdbcType=JdbcType.VARCHAR),
        @Result(column="dict_key", property="dictKey", jdbcType=JdbcType.INTEGER),
        @Result(column="dict_val", property="dictVal", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_uid", property="createUid", jdbcType=JdbcType.INTEGER),
        @Result(column="update_uid", property="updateUid", jdbcType=JdbcType.INTEGER)
    })
    List<ABusinessDict> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_BUSINESS_DICT
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    @Update({
        "update A_BUSINESS_DICT",
        "set dict_class = #{dictClass,jdbcType=VARCHAR},",
          "dict_key = #{dictKey,jdbcType=INTEGER},",
          "dict_val = #{dictVal,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "create_uid = #{createUid,jdbcType=INTEGER},",
          "update_uid = #{updateUid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ABusinessDict record);
}