package com.amor.orm.mapper;

import com.amor.orm.model.AContractInfo;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface AContractInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_CONTRACT_INFO
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    @Delete({
        "delete from A_CONTRACT_INFO",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_CONTRACT_INFO
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    @Insert({
        "insert into A_CONTRACT_INFO (id, contract_type, ",
        "user_id, sign_date, ",
        "first_party, card_type, ",
        "card_no, phone, total, ",
        "remain_sum, deposit, ",
        "first_trial_date, measure_date, ",
        "second_trial_date, fetch_date, ",
        "return_date, create_uid, ",
        "note)",
        "values (#{id,jdbcType=INTEGER}, #{contractType,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{signDate,jdbcType=TIMESTAMP}, ",
        "#{firstParty,jdbcType=VARCHAR}, #{cardType,jdbcType=INTEGER}, ",
        "#{cardNo,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, #{total,jdbcType=DOUBLE}, ",
        "#{remainSum,jdbcType=DOUBLE}, #{deposit,jdbcType=DOUBLE}, ",
        "#{firstTrialDate,jdbcType=TIMESTAMP}, #{measureDate,jdbcType=TIMESTAMP}, ",
        "#{secondTrialDate,jdbcType=TIMESTAMP}, #{fetchDate,jdbcType=TIMESTAMP}, ",
        "#{returnDate,jdbcType=TIMESTAMP}, #{createUid,jdbcType=INTEGER}, ",
        "#{note,jdbcType=LONGVARCHAR})"
    })
    int insert(AContractInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_CONTRACT_INFO
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    @Select({
        "select",
        "id, contract_type, user_id, sign_date, first_party, card_type, card_no, phone, ",
        "total, remain_sum, deposit, first_trial_date, measure_date, second_trial_date, ",
        "fetch_date, return_date, create_uid, note",
        "from A_CONTRACT_INFO",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="contract_type", property="contractType", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="sign_date", property="signDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="first_party", property="firstParty", jdbcType=JdbcType.VARCHAR),
        @Result(column="card_type", property="cardType", jdbcType=JdbcType.INTEGER),
        @Result(column="card_no", property="cardNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="total", property="total", jdbcType=JdbcType.DOUBLE),
        @Result(column="remain_sum", property="remainSum", jdbcType=JdbcType.DOUBLE),
        @Result(column="deposit", property="deposit", jdbcType=JdbcType.DOUBLE),
        @Result(column="first_trial_date", property="firstTrialDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="measure_date", property="measureDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="second_trial_date", property="secondTrialDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="fetch_date", property="fetchDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="return_date", property="returnDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_uid", property="createUid", jdbcType=JdbcType.INTEGER),
        @Result(column="note", property="note", jdbcType=JdbcType.LONGVARCHAR)
    })
    AContractInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_CONTRACT_INFO
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    @Select({
        "select",
        "id, contract_type, user_id, sign_date, first_party, card_type, card_no, phone, ",
        "total, remain_sum, deposit, first_trial_date, measure_date, second_trial_date, ",
        "fetch_date, return_date, create_uid, note",
        "from A_CONTRACT_INFO"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="contract_type", property="contractType", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="sign_date", property="signDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="first_party", property="firstParty", jdbcType=JdbcType.VARCHAR),
        @Result(column="card_type", property="cardType", jdbcType=JdbcType.INTEGER),
        @Result(column="card_no", property="cardNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="total", property="total", jdbcType=JdbcType.DOUBLE),
        @Result(column="remain_sum", property="remainSum", jdbcType=JdbcType.DOUBLE),
        @Result(column="deposit", property="deposit", jdbcType=JdbcType.DOUBLE),
        @Result(column="first_trial_date", property="firstTrialDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="measure_date", property="measureDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="second_trial_date", property="secondTrialDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="fetch_date", property="fetchDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="return_date", property="returnDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_uid", property="createUid", jdbcType=JdbcType.INTEGER),
        @Result(column="note", property="note", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<AContractInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_CONTRACT_INFO
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    @Update({
        "update A_CONTRACT_INFO",
        "set contract_type = #{contractType,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "sign_date = #{signDate,jdbcType=TIMESTAMP},",
          "first_party = #{firstParty,jdbcType=VARCHAR},",
          "card_type = #{cardType,jdbcType=INTEGER},",
          "card_no = #{cardNo,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "total = #{total,jdbcType=DOUBLE},",
          "remain_sum = #{remainSum,jdbcType=DOUBLE},",
          "deposit = #{deposit,jdbcType=DOUBLE},",
          "first_trial_date = #{firstTrialDate,jdbcType=TIMESTAMP},",
          "measure_date = #{measureDate,jdbcType=TIMESTAMP},",
          "second_trial_date = #{secondTrialDate,jdbcType=TIMESTAMP},",
          "fetch_date = #{fetchDate,jdbcType=TIMESTAMP},",
          "return_date = #{returnDate,jdbcType=TIMESTAMP},",
          "create_uid = #{createUid,jdbcType=INTEGER},",
          "note = #{note,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AContractInfo record);
}