package com.amor.orm.mapper;

import com.amor.core.base.BaseMapper;
import com.amor.orm.model.APermission;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface APermissionMapper extends BaseMapper<APermission, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_PERMISSION
     *
     * @mbggenerated Sun Oct 16 16:13:26 CST 2016
     */
    @Delete({
        "delete from A_PERMISSION",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_PERMISSION
     *
     * @mbggenerated Sun Oct 16 16:13:26 CST 2016
     */
    @Insert({
        "insert into A_PERMISSION (id, role_id, ",
        "permission_code, operation_code, ",
        "permission_name, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER}, ",
        "#{permissionCode,jdbcType=VARCHAR}, #{operationCode,jdbcType=VARCHAR}, ",
        "#{permissionName,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(APermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_PERMISSION
     *
     * @mbggenerated Sun Oct 16 16:13:26 CST 2016
     */
    @Select({
        "select",
        "id, role_id, permission_code, operation_code, permission_name, create_time, ",
        "update_time",
        "from A_PERMISSION",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.INTEGER),
        @Result(column="permission_code", property="permissionCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="operation_code", property="operationCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="permission_name", property="permissionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    APermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_PERMISSION
     *
     * @mbggenerated Sun Oct 16 16:13:26 CST 2016
     */
    @Select({
        "select",
        "id, role_id, permission_code, operation_code, permission_name, create_time, ",
        "update_time",
        "from A_PERMISSION"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.INTEGER),
        @Result(column="permission_code", property="permissionCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="operation_code", property="operationCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="permission_name", property="permissionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<APermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_PERMISSION
     *
     * @mbggenerated Sun Oct 16 16:13:26 CST 2016
     */
    @Update({
        "update A_PERMISSION",
        "set role_id = #{roleId,jdbcType=INTEGER},",
          "permission_code = #{permissionCode,jdbcType=VARCHAR},",
          "operation_code = #{operationCode,jdbcType=VARCHAR},",
          "permission_name = #{permissionName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(APermission record);
}