package com.amor.orm.mapper;

import com.amor.orm.model.AWedding;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface AWeddingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_WEDDING
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    @Delete({
        "delete from A_WEDDING",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_WEDDING
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    @Insert({
        "insert into A_WEDDING (id, customer_id, ",
        "wedding_date)",
        "values (#{id,jdbcType=INTEGER}, #{customerId,jdbcType=INTEGER}, ",
        "#{weddingDate,jdbcType=TIMESTAMP})"
    })
    int insert(AWedding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_WEDDING
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    @Select({
        "select",
        "id, customer_id, wedding_date",
        "from A_WEDDING",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.INTEGER),
        @Result(column="wedding_date", property="weddingDate", jdbcType=JdbcType.TIMESTAMP)
    })
    AWedding selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_WEDDING
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    @Select({
        "select",
        "id, customer_id, wedding_date",
        "from A_WEDDING"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.INTEGER),
        @Result(column="wedding_date", property="weddingDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<AWedding> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_WEDDING
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    @Update({
        "update A_WEDDING",
        "set customer_id = #{customerId,jdbcType=INTEGER},",
          "wedding_date = #{weddingDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AWedding record);
}