package com.amor.web.model;

public class ACustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.person_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.status
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.shape
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String shape;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.weight
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.height
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.height_heel
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Double heightHeel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.height_waist
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Double heightWaist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.length_crotch_d
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Double lengthCrotchD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.length_skirt
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Double lengthSkirt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.length_arm
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Double lengthArm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.length_tail
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Double lengthTail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.bust
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String bust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.bust_d
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String bustD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.waist
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String waist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.hipline
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String hipline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.neck
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String neck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.arm
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String arm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.leg
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String leg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_CUSTOMER.wrist
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String wrist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.id
     *
     * @return the value of A_CUSTOMER.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.id
     *
     * @param id the value for A_CUSTOMER.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.person_id
     *
     * @return the value of A_CUSTOMER.person_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.person_id
     *
     * @param personId the value for A_CUSTOMER.person_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.status
     *
     * @return the value of A_CUSTOMER.status
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.status
     *
     * @param status the value for A_CUSTOMER.status
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.shape
     *
     * @return the value of A_CUSTOMER.shape
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getShape() {
        return shape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.shape
     *
     * @param shape the value for A_CUSTOMER.shape
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setShape(String shape) {
        this.shape = shape == null ? null : shape.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.weight
     *
     * @return the value of A_CUSTOMER.weight
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.weight
     *
     * @param weight the value for A_CUSTOMER.weight
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.height
     *
     * @return the value of A_CUSTOMER.height
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.height
     *
     * @param height the value for A_CUSTOMER.height
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.height_heel
     *
     * @return the value of A_CUSTOMER.height_heel
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Double getHeightHeel() {
        return heightHeel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.height_heel
     *
     * @param heightHeel the value for A_CUSTOMER.height_heel
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setHeightHeel(Double heightHeel) {
        this.heightHeel = heightHeel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.height_waist
     *
     * @return the value of A_CUSTOMER.height_waist
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Double getHeightWaist() {
        return heightWaist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.height_waist
     *
     * @param heightWaist the value for A_CUSTOMER.height_waist
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setHeightWaist(Double heightWaist) {
        this.heightWaist = heightWaist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.length_crotch_d
     *
     * @return the value of A_CUSTOMER.length_crotch_d
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Double getLengthCrotchD() {
        return lengthCrotchD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.length_crotch_d
     *
     * @param lengthCrotchD the value for A_CUSTOMER.length_crotch_d
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setLengthCrotchD(Double lengthCrotchD) {
        this.lengthCrotchD = lengthCrotchD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.length_skirt
     *
     * @return the value of A_CUSTOMER.length_skirt
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Double getLengthSkirt() {
        return lengthSkirt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.length_skirt
     *
     * @param lengthSkirt the value for A_CUSTOMER.length_skirt
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setLengthSkirt(Double lengthSkirt) {
        this.lengthSkirt = lengthSkirt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.length_arm
     *
     * @return the value of A_CUSTOMER.length_arm
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Double getLengthArm() {
        return lengthArm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.length_arm
     *
     * @param lengthArm the value for A_CUSTOMER.length_arm
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setLengthArm(Double lengthArm) {
        this.lengthArm = lengthArm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.length_tail
     *
     * @return the value of A_CUSTOMER.length_tail
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Double getLengthTail() {
        return lengthTail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.length_tail
     *
     * @param lengthTail the value for A_CUSTOMER.length_tail
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setLengthTail(Double lengthTail) {
        this.lengthTail = lengthTail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.bust
     *
     * @return the value of A_CUSTOMER.bust
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getBust() {
        return bust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.bust
     *
     * @param bust the value for A_CUSTOMER.bust
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setBust(String bust) {
        this.bust = bust == null ? null : bust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.bust_d
     *
     * @return the value of A_CUSTOMER.bust_d
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getBustD() {
        return bustD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.bust_d
     *
     * @param bustD the value for A_CUSTOMER.bust_d
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setBustD(String bustD) {
        this.bustD = bustD == null ? null : bustD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.waist
     *
     * @return the value of A_CUSTOMER.waist
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getWaist() {
        return waist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.waist
     *
     * @param waist the value for A_CUSTOMER.waist
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setWaist(String waist) {
        this.waist = waist == null ? null : waist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.hipline
     *
     * @return the value of A_CUSTOMER.hipline
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getHipline() {
        return hipline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.hipline
     *
     * @param hipline the value for A_CUSTOMER.hipline
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setHipline(String hipline) {
        this.hipline = hipline == null ? null : hipline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.neck
     *
     * @return the value of A_CUSTOMER.neck
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getNeck() {
        return neck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.neck
     *
     * @param neck the value for A_CUSTOMER.neck
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setNeck(String neck) {
        this.neck = neck == null ? null : neck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.arm
     *
     * @return the value of A_CUSTOMER.arm
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getArm() {
        return arm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.arm
     *
     * @param arm the value for A_CUSTOMER.arm
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setArm(String arm) {
        this.arm = arm == null ? null : arm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.leg
     *
     * @return the value of A_CUSTOMER.leg
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getLeg() {
        return leg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.leg
     *
     * @param leg the value for A_CUSTOMER.leg
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setLeg(String leg) {
        this.leg = leg == null ? null : leg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_CUSTOMER.wrist
     *
     * @return the value of A_CUSTOMER.wrist
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getWrist() {
        return wrist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_CUSTOMER.wrist
     *
     * @param wrist the value for A_CUSTOMER.wrist
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setWrist(String wrist) {
        this.wrist = wrist == null ? null : wrist.trim();
    }
}