package com.amor.web.model;

public class ALogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_LOGIN.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_LOGIN.persion_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer persionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_LOGIN.username
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_LOGIN.password
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_LOGIN.status
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_LOGIN.login_code
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String loginCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_LOGIN.login_from
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String loginFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_LOGIN.id
     *
     * @return the value of A_LOGIN.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_LOGIN.id
     *
     * @param id the value for A_LOGIN.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_LOGIN.persion_id
     *
     * @return the value of A_LOGIN.persion_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getPersionId() {
        return persionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_LOGIN.persion_id
     *
     * @param persionId the value for A_LOGIN.persion_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setPersionId(Integer persionId) {
        this.persionId = persionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_LOGIN.username
     *
     * @return the value of A_LOGIN.username
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_LOGIN.username
     *
     * @param username the value for A_LOGIN.username
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_LOGIN.password
     *
     * @return the value of A_LOGIN.password
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_LOGIN.password
     *
     * @param password the value for A_LOGIN.password
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_LOGIN.status
     *
     * @return the value of A_LOGIN.status
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_LOGIN.status
     *
     * @param status the value for A_LOGIN.status
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_LOGIN.login_code
     *
     * @return the value of A_LOGIN.login_code
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getLoginCode() {
        return loginCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_LOGIN.login_code
     *
     * @param loginCode the value for A_LOGIN.login_code
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setLoginCode(String loginCode) {
        this.loginCode = loginCode == null ? null : loginCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_LOGIN.login_from
     *
     * @return the value of A_LOGIN.login_from
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getLoginFrom() {
        return loginFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_LOGIN.login_from
     *
     * @param loginFrom the value for A_LOGIN.login_from
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setLoginFrom(String loginFrom) {
        this.loginFrom = loginFrom == null ? null : loginFrom.trim();
    }
}