package com.amor.web.model;

public class APerson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERSON.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERSON.name
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERSON.gender
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERSON.identity_code
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String identityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERSON.tel
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERSON.email
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERSON.id
     *
     * @return the value of A_PERSON.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERSON.id
     *
     * @param id the value for A_PERSON.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERSON.name
     *
     * @return the value of A_PERSON.name
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERSON.name
     *
     * @param name the value for A_PERSON.name
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERSON.gender
     *
     * @return the value of A_PERSON.gender
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERSON.gender
     *
     * @param gender the value for A_PERSON.gender
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERSON.identity_code
     *
     * @return the value of A_PERSON.identity_code
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getIdentityCode() {
        return identityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERSON.identity_code
     *
     * @param identityCode the value for A_PERSON.identity_code
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setIdentityCode(String identityCode) {
        this.identityCode = identityCode == null ? null : identityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERSON.tel
     *
     * @return the value of A_PERSON.tel
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERSON.tel
     *
     * @param tel the value for A_PERSON.tel
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERSON.email
     *
     * @return the value of A_PERSON.email
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERSON.email
     *
     * @param email the value for A_PERSON.email
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}