package com.amor.web.model;

import java.util.Date;

public class ARole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_ROLE.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_ROLE.name
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_ROLE.type
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_ROLE.memo
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_ROLE.create_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_ROLE.update_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_ROLE.id
     *
     * @return the value of A_ROLE.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_ROLE.id
     *
     * @param id the value for A_ROLE.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_ROLE.name
     *
     * @return the value of A_ROLE.name
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_ROLE.name
     *
     * @param name the value for A_ROLE.name
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_ROLE.type
     *
     * @return the value of A_ROLE.type
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_ROLE.type
     *
     * @param type the value for A_ROLE.type
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_ROLE.memo
     *
     * @return the value of A_ROLE.memo
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_ROLE.memo
     *
     * @param memo the value for A_ROLE.memo
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_ROLE.create_time
     *
     * @return the value of A_ROLE.create_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_ROLE.create_time
     *
     * @param createTime the value for A_ROLE.create_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_ROLE.update_time
     *
     * @return the value of A_ROLE.update_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_ROLE.update_time
     *
     * @param updateTime the value for A_ROLE.update_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}