package com.amor.web.model;

public class AStaff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STAFF.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STAFF.person_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STAFF.store_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STAFF.status
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STAFF.id
     *
     * @return the value of A_STAFF.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STAFF.id
     *
     * @param id the value for A_STAFF.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STAFF.person_id
     *
     * @return the value of A_STAFF.person_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STAFF.person_id
     *
     * @param personId the value for A_STAFF.person_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STAFF.store_id
     *
     * @return the value of A_STAFF.store_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STAFF.store_id
     *
     * @param storeId the value for A_STAFF.store_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STAFF.status
     *
     * @return the value of A_STAFF.status
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STAFF.status
     *
     * @param status the value for A_STAFF.status
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}