package com.amor.web.model;

import java.util.Date;

public class AStore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE.name
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE.address
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE.tel
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE.open_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Date openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE.close_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Date closeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE.id
     *
     * @return the value of A_STORE.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE.id
     *
     * @param id the value for A_STORE.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE.name
     *
     * @return the value of A_STORE.name
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE.name
     *
     * @param name the value for A_STORE.name
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE.address
     *
     * @return the value of A_STORE.address
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE.address
     *
     * @param address the value for A_STORE.address
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE.tel
     *
     * @return the value of A_STORE.tel
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE.tel
     *
     * @param tel the value for A_STORE.tel
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE.open_time
     *
     * @return the value of A_STORE.open_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE.open_time
     *
     * @param openTime the value for A_STORE.open_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE.close_time
     *
     * @return the value of A_STORE.close_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE.close_time
     *
     * @param closeTime the value for A_STORE.close_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }
}