package com.amor.web.model;

import java.util.Date;

public class AStoreInventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE_INVENTORY.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE_INVENTORY.item_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE_INVENTORY.store_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE_INVENTORY.number
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE_INVENTORY.create_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE_INVENTORY.update_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE_INVENTORY.create_uid
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_STORE_INVENTORY.update_uid
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer updateUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE_INVENTORY.id
     *
     * @return the value of A_STORE_INVENTORY.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE_INVENTORY.id
     *
     * @param id the value for A_STORE_INVENTORY.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE_INVENTORY.item_id
     *
     * @return the value of A_STORE_INVENTORY.item_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE_INVENTORY.item_id
     *
     * @param itemId the value for A_STORE_INVENTORY.item_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE_INVENTORY.store_id
     *
     * @return the value of A_STORE_INVENTORY.store_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE_INVENTORY.store_id
     *
     * @param storeId the value for A_STORE_INVENTORY.store_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE_INVENTORY.number
     *
     * @return the value of A_STORE_INVENTORY.number
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE_INVENTORY.number
     *
     * @param number the value for A_STORE_INVENTORY.number
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE_INVENTORY.create_time
     *
     * @return the value of A_STORE_INVENTORY.create_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE_INVENTORY.create_time
     *
     * @param createTime the value for A_STORE_INVENTORY.create_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE_INVENTORY.update_time
     *
     * @return the value of A_STORE_INVENTORY.update_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE_INVENTORY.update_time
     *
     * @param updateTime the value for A_STORE_INVENTORY.update_time
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE_INVENTORY.create_uid
     *
     * @return the value of A_STORE_INVENTORY.create_uid
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE_INVENTORY.create_uid
     *
     * @param createUid the value for A_STORE_INVENTORY.create_uid
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_STORE_INVENTORY.update_uid
     *
     * @return the value of A_STORE_INVENTORY.update_uid
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_STORE_INVENTORY.update_uid
     *
     * @param updateUid the value for A_STORE_INVENTORY.update_uid
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }
}