package com.amor.web.model;

import java.util.Date;

public class AWedding {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_WEDDING.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_WEDDING.customer_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_WEDDING.wedding_date
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    private Date weddingDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_WEDDING.id
     *
     * @return the value of A_WEDDING.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_WEDDING.id
     *
     * @param id the value for A_WEDDING.id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_WEDDING.customer_id
     *
     * @return the value of A_WEDDING.customer_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_WEDDING.customer_id
     *
     * @param customerId the value for A_WEDDING.customer_id
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_WEDDING.wedding_date
     *
     * @return the value of A_WEDDING.wedding_date
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public Date getWeddingDate() {
        return weddingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_WEDDING.wedding_date
     *
     * @param weddingDate the value for A_WEDDING.wedding_date
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    public void setWeddingDate(Date weddingDate) {
        this.weddingDate = weddingDate;
    }
}