package com.amor.web.mapper;

import com.amor.web.model.AOrderDetail;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface AOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_ORDER_DETAIL
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    @Delete({
        "delete from A_ORDER_DETAIL",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_ORDER_DETAIL
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    @Insert({
        "insert into A_ORDER_DETAIL (id, deal_id, ",
        "status, mortgage, ",
        "back_time, staff_id, ",
        "comment)",
        "values (#{id,jdbcType=INTEGER}, #{dealId,jdbcType=INTEGER}, ",
        "#{status,jdbcType=VARCHAR}, #{mortgage,jdbcType=VARCHAR}, ",
        "#{backTime,jdbcType=TIMESTAMP}, #{staffId,jdbcType=INTEGER}, ",
        "#{comment,jdbcType=VARCHAR})"
    })
    int insert(AOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_ORDER_DETAIL
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    @Select({
        "select",
        "id, deal_id, status, mortgage, back_time, staff_id, comment",
        "from A_ORDER_DETAIL",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="deal_id", property="dealId", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="mortgage", property="mortgage", jdbcType=JdbcType.VARCHAR),
        @Result(column="back_time", property="backTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="staff_id", property="staffId", jdbcType=JdbcType.INTEGER),
        @Result(column="comment", property="comment", jdbcType=JdbcType.VARCHAR)
    })
    AOrderDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_ORDER_DETAIL
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    @Select({
        "select",
        "id, deal_id, status, mortgage, back_time, staff_id, comment",
        "from A_ORDER_DETAIL"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="deal_id", property="dealId", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="mortgage", property="mortgage", jdbcType=JdbcType.VARCHAR),
        @Result(column="back_time", property="backTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="staff_id", property="staffId", jdbcType=JdbcType.INTEGER),
        @Result(column="comment", property="comment", jdbcType=JdbcType.VARCHAR)
    })
    List<AOrderDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A_ORDER_DETAIL
     *
     * @mbggenerated Mon Sep 05 15:00:17 CST 2016
     */
    @Update({
        "update A_ORDER_DETAIL",
        "set deal_id = #{dealId,jdbcType=INTEGER},",
          "status = #{status,jdbcType=VARCHAR},",
          "mortgage = #{mortgage,jdbcType=VARCHAR},",
          "back_time = #{backTime,jdbcType=TIMESTAMP},",
          "staff_id = #{staffId,jdbcType=INTEGER},",
          "comment = #{comment,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AOrderDetail record);
}