package com.amor.orm.model;

import java.util.Date;

public class ABusinessDict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_BUSINESS_DICT.id
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_BUSINESS_DICT.dict_class
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    private String dictClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_BUSINESS_DICT.dict_key
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    private Integer dictKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_BUSINESS_DICT.dict_val
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    private String dictVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_BUSINESS_DICT.create_time
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_BUSINESS_DICT.update_time
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_BUSINESS_DICT.create_uid
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_BUSINESS_DICT.update_uid
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    private Integer updateUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_BUSINESS_DICT.id
     *
     * @return the value of A_BUSINESS_DICT.id
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_BUSINESS_DICT.id
     *
     * @param id the value for A_BUSINESS_DICT.id
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_BUSINESS_DICT.dict_class
     *
     * @return the value of A_BUSINESS_DICT.dict_class
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public String getDictClass() {
        return dictClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_BUSINESS_DICT.dict_class
     *
     * @param dictClass the value for A_BUSINESS_DICT.dict_class
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public void setDictClass(String dictClass) {
        this.dictClass = dictClass == null ? null : dictClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_BUSINESS_DICT.dict_key
     *
     * @return the value of A_BUSINESS_DICT.dict_key
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public Integer getDictKey() {
        return dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_BUSINESS_DICT.dict_key
     *
     * @param dictKey the value for A_BUSINESS_DICT.dict_key
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public void setDictKey(Integer dictKey) {
        this.dictKey = dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_BUSINESS_DICT.dict_val
     *
     * @return the value of A_BUSINESS_DICT.dict_val
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public String getDictVal() {
        return dictVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_BUSINESS_DICT.dict_val
     *
     * @param dictVal the value for A_BUSINESS_DICT.dict_val
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public void setDictVal(String dictVal) {
        this.dictVal = dictVal == null ? null : dictVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_BUSINESS_DICT.create_time
     *
     * @return the value of A_BUSINESS_DICT.create_time
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_BUSINESS_DICT.create_time
     *
     * @param createTime the value for A_BUSINESS_DICT.create_time
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_BUSINESS_DICT.update_time
     *
     * @return the value of A_BUSINESS_DICT.update_time
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_BUSINESS_DICT.update_time
     *
     * @param updateTime the value for A_BUSINESS_DICT.update_time
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_BUSINESS_DICT.create_uid
     *
     * @return the value of A_BUSINESS_DICT.create_uid
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_BUSINESS_DICT.create_uid
     *
     * @param createUid the value for A_BUSINESS_DICT.create_uid
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_BUSINESS_DICT.update_uid
     *
     * @return the value of A_BUSINESS_DICT.update_uid
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_BUSINESS_DICT.update_uid
     *
     * @param updateUid the value for A_BUSINESS_DICT.update_uid
     *
     * @mbggenerated Fri Sep 16 21:54:57 CST 2016
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }
}