package com.amor.orm.model;

import java.util.Date;

public class APermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERMISSION.id
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERMISSION.role_id
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERMISSION.privilege_code
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    private String privilegeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERMISSION.operation_code
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    private String operationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERMISSION.privilege_name
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    private String privilegeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERMISSION.create_time
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PERMISSION.update_time
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERMISSION.id
     *
     * @return the value of A_PERMISSION.id
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERMISSION.id
     *
     * @param id the value for A_PERMISSION.id
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERMISSION.role_id
     *
     * @return the value of A_PERMISSION.role_id
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERMISSION.role_id
     *
     * @param roleId the value for A_PERMISSION.role_id
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERMISSION.privilege_code
     *
     * @return the value of A_PERMISSION.privilege_code
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public String getPrivilegeCode() {
        return privilegeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERMISSION.privilege_code
     *
     * @param privilegeCode the value for A_PERMISSION.privilege_code
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public void setPrivilegeCode(String privilegeCode) {
        this.privilegeCode = privilegeCode == null ? null : privilegeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERMISSION.operation_code
     *
     * @return the value of A_PERMISSION.operation_code
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public String getOperationCode() {
        return operationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERMISSION.operation_code
     *
     * @param operationCode the value for A_PERMISSION.operation_code
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public void setOperationCode(String operationCode) {
        this.operationCode = operationCode == null ? null : operationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERMISSION.privilege_name
     *
     * @return the value of A_PERMISSION.privilege_name
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public String getPrivilegeName() {
        return privilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERMISSION.privilege_name
     *
     * @param privilegeName the value for A_PERMISSION.privilege_name
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName == null ? null : privilegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERMISSION.create_time
     *
     * @return the value of A_PERMISSION.create_time
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERMISSION.create_time
     *
     * @param createTime the value for A_PERMISSION.create_time
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PERMISSION.update_time
     *
     * @return the value of A_PERMISSION.update_time
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PERMISSION.update_time
     *
     * @param updateTime the value for A_PERMISSION.update_time
     *
     * @mbggenerated Fri Sep 16 22:11:18 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}