package com.amor.orm.model;

import java.util.Date;

public class AProductImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.id
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.product_id
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.img_path
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.create_datetime
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    private Date createDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.id
     *
     * @return the value of A_PRODUCT_IMAGE.id
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.id
     *
     * @param id the value for A_PRODUCT_IMAGE.id
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.product_id
     *
     * @return the value of A_PRODUCT_IMAGE.product_id
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.product_id
     *
     * @param productId the value for A_PRODUCT_IMAGE.product_id
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.img_path
     *
     * @return the value of A_PRODUCT_IMAGE.img_path
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.img_path
     *
     * @param imgPath the value for A_PRODUCT_IMAGE.img_path
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.create_datetime
     *
     * @return the value of A_PRODUCT_IMAGE.create_datetime
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.create_datetime
     *
     * @param createDatetime the value for A_PRODUCT_IMAGE.create_datetime
     *
     * @mbggenerated Sun Oct 23 14:40:44 CST 2016
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }
}