package com.amor.orm.model;

import java.util.Date;

public class AProductImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.id
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.product_id
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.img_path
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.img_src
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private String imgSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.title
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.description
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.priority
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT_IMAGE.create_datetime
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Date createDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.id
     *
     * @return the value of A_PRODUCT_IMAGE.id
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.id
     *
     * @param id the value for A_PRODUCT_IMAGE.id
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.product_id
     *
     * @return the value of A_PRODUCT_IMAGE.product_id
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.product_id
     *
     * @param productId the value for A_PRODUCT_IMAGE.product_id
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.img_path
     *
     * @return the value of A_PRODUCT_IMAGE.img_path
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.img_path
     *
     * @param imgPath the value for A_PRODUCT_IMAGE.img_path
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.img_src
     *
     * @return the value of A_PRODUCT_IMAGE.img_src
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public String getImgSrc() {
        return imgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.img_src
     *
     * @param imgSrc the value for A_PRODUCT_IMAGE.img_src
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc == null ? null : imgSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.title
     *
     * @return the value of A_PRODUCT_IMAGE.title
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.title
     *
     * @param title the value for A_PRODUCT_IMAGE.title
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.description
     *
     * @return the value of A_PRODUCT_IMAGE.description
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.description
     *
     * @param description the value for A_PRODUCT_IMAGE.description
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.priority
     *
     * @return the value of A_PRODUCT_IMAGE.priority
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.priority
     *
     * @param priority the value for A_PRODUCT_IMAGE.priority
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT_IMAGE.create_datetime
     *
     * @return the value of A_PRODUCT_IMAGE.create_datetime
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT_IMAGE.create_datetime
     *
     * @param createDatetime the value for A_PRODUCT_IMAGE.create_datetime
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }
}