package com.amor.orm.model;

import java.util.Date;

public class AProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.id
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.item_code
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private String itemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.item_type
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer itemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.trends
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private String trends;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.silhouette
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer silhouette;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.neckline
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer neckline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.collar_stays
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer collarStays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.placket
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer placket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.bust
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer bust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.waistline
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer waistline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.shoulder
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer shoulder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.back
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer back;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.hips
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer hips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.sleeve
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer sleeve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.white_collar_sleeve
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer whiteCollarSleeve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.cuff_words
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer cuffWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.cuff_words_type
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer cuffWordsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.pocket
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer pocket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.pants
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer pants;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.version
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.color
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.size
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.material
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private String material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.others
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.price_cost
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Double priceCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.price_agent
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Double priceAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.price_rent
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Double priceRent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.price_sell
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Double priceSell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.price_alliance
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Double priceAlliance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.create_time
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.update_time
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.create_uid
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_PRODUCT.update_uid
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    private Integer updateUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.id
     *
     * @return the value of A_PRODUCT.id
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.id
     *
     * @param id the value for A_PRODUCT.id
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.item_code
     *
     * @return the value of A_PRODUCT.item_code
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.item_code
     *
     * @param itemCode the value for A_PRODUCT.item_code
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.item_type
     *
     * @return the value of A_PRODUCT.item_type
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.item_type
     *
     * @param itemType the value for A_PRODUCT.item_type
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.trends
     *
     * @return the value of A_PRODUCT.trends
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public String getTrends() {
        return trends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.trends
     *
     * @param trends the value for A_PRODUCT.trends
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setTrends(String trends) {
        this.trends = trends == null ? null : trends.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.silhouette
     *
     * @return the value of A_PRODUCT.silhouette
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getSilhouette() {
        return silhouette;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.silhouette
     *
     * @param silhouette the value for A_PRODUCT.silhouette
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setSilhouette(Integer silhouette) {
        this.silhouette = silhouette;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.neckline
     *
     * @return the value of A_PRODUCT.neckline
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getNeckline() {
        return neckline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.neckline
     *
     * @param neckline the value for A_PRODUCT.neckline
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setNeckline(Integer neckline) {
        this.neckline = neckline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.collar_stays
     *
     * @return the value of A_PRODUCT.collar_stays
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getCollarStays() {
        return collarStays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.collar_stays
     *
     * @param collarStays the value for A_PRODUCT.collar_stays
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setCollarStays(Integer collarStays) {
        this.collarStays = collarStays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.placket
     *
     * @return the value of A_PRODUCT.placket
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getPlacket() {
        return placket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.placket
     *
     * @param placket the value for A_PRODUCT.placket
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setPlacket(Integer placket) {
        this.placket = placket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.bust
     *
     * @return the value of A_PRODUCT.bust
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getBust() {
        return bust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.bust
     *
     * @param bust the value for A_PRODUCT.bust
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setBust(Integer bust) {
        this.bust = bust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.waistline
     *
     * @return the value of A_PRODUCT.waistline
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getWaistline() {
        return waistline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.waistline
     *
     * @param waistline the value for A_PRODUCT.waistline
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setWaistline(Integer waistline) {
        this.waistline = waistline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.shoulder
     *
     * @return the value of A_PRODUCT.shoulder
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getShoulder() {
        return shoulder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.shoulder
     *
     * @param shoulder the value for A_PRODUCT.shoulder
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setShoulder(Integer shoulder) {
        this.shoulder = shoulder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.back
     *
     * @return the value of A_PRODUCT.back
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getBack() {
        return back;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.back
     *
     * @param back the value for A_PRODUCT.back
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setBack(Integer back) {
        this.back = back;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.hips
     *
     * @return the value of A_PRODUCT.hips
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getHips() {
        return hips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.hips
     *
     * @param hips the value for A_PRODUCT.hips
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setHips(Integer hips) {
        this.hips = hips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.sleeve
     *
     * @return the value of A_PRODUCT.sleeve
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getSleeve() {
        return sleeve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.sleeve
     *
     * @param sleeve the value for A_PRODUCT.sleeve
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setSleeve(Integer sleeve) {
        this.sleeve = sleeve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.white_collar_sleeve
     *
     * @return the value of A_PRODUCT.white_collar_sleeve
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getWhiteCollarSleeve() {
        return whiteCollarSleeve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.white_collar_sleeve
     *
     * @param whiteCollarSleeve the value for A_PRODUCT.white_collar_sleeve
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setWhiteCollarSleeve(Integer whiteCollarSleeve) {
        this.whiteCollarSleeve = whiteCollarSleeve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.cuff_words
     *
     * @return the value of A_PRODUCT.cuff_words
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getCuffWords() {
        return cuffWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.cuff_words
     *
     * @param cuffWords the value for A_PRODUCT.cuff_words
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setCuffWords(Integer cuffWords) {
        this.cuffWords = cuffWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.cuff_words_type
     *
     * @return the value of A_PRODUCT.cuff_words_type
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getCuffWordsType() {
        return cuffWordsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.cuff_words_type
     *
     * @param cuffWordsType the value for A_PRODUCT.cuff_words_type
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setCuffWordsType(Integer cuffWordsType) {
        this.cuffWordsType = cuffWordsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.pocket
     *
     * @return the value of A_PRODUCT.pocket
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getPocket() {
        return pocket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.pocket
     *
     * @param pocket the value for A_PRODUCT.pocket
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setPocket(Integer pocket) {
        this.pocket = pocket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.pants
     *
     * @return the value of A_PRODUCT.pants
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getPants() {
        return pants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.pants
     *
     * @param pants the value for A_PRODUCT.pants
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setPants(Integer pants) {
        this.pants = pants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.version
     *
     * @return the value of A_PRODUCT.version
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.version
     *
     * @param version the value for A_PRODUCT.version
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.color
     *
     * @return the value of A_PRODUCT.color
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.color
     *
     * @param color the value for A_PRODUCT.color
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setColor(Integer color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.size
     *
     * @return the value of A_PRODUCT.size
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.size
     *
     * @param size the value for A_PRODUCT.size
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.material
     *
     * @return the value of A_PRODUCT.material
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.material
     *
     * @param material the value for A_PRODUCT.material
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.others
     *
     * @return the value of A_PRODUCT.others
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.others
     *
     * @param others the value for A_PRODUCT.others
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.price_cost
     *
     * @return the value of A_PRODUCT.price_cost
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Double getPriceCost() {
        return priceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.price_cost
     *
     * @param priceCost the value for A_PRODUCT.price_cost
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setPriceCost(Double priceCost) {
        this.priceCost = priceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.price_agent
     *
     * @return the value of A_PRODUCT.price_agent
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Double getPriceAgent() {
        return priceAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.price_agent
     *
     * @param priceAgent the value for A_PRODUCT.price_agent
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setPriceAgent(Double priceAgent) {
        this.priceAgent = priceAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.price_rent
     *
     * @return the value of A_PRODUCT.price_rent
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Double getPriceRent() {
        return priceRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.price_rent
     *
     * @param priceRent the value for A_PRODUCT.price_rent
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setPriceRent(Double priceRent) {
        this.priceRent = priceRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.price_sell
     *
     * @return the value of A_PRODUCT.price_sell
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Double getPriceSell() {
        return priceSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.price_sell
     *
     * @param priceSell the value for A_PRODUCT.price_sell
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setPriceSell(Double priceSell) {
        this.priceSell = priceSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.price_alliance
     *
     * @return the value of A_PRODUCT.price_alliance
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Double getPriceAlliance() {
        return priceAlliance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.price_alliance
     *
     * @param priceAlliance the value for A_PRODUCT.price_alliance
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setPriceAlliance(Double priceAlliance) {
        this.priceAlliance = priceAlliance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.create_time
     *
     * @return the value of A_PRODUCT.create_time
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.create_time
     *
     * @param createTime the value for A_PRODUCT.create_time
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.update_time
     *
     * @return the value of A_PRODUCT.update_time
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.update_time
     *
     * @param updateTime the value for A_PRODUCT.update_time
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.create_uid
     *
     * @return the value of A_PRODUCT.create_uid
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.create_uid
     *
     * @param createUid the value for A_PRODUCT.create_uid
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_PRODUCT.update_uid
     *
     * @return the value of A_PRODUCT.update_uid
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_PRODUCT.update_uid
     *
     * @param updateUid the value for A_PRODUCT.update_uid
     *
     * @mbggenerated Sun Nov 06 15:37:00 CST 2016
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }
}