package com.amor.orm.model;

public class ARoleWebPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_ROLE_WEB_PERMISSION.id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_ROLE_WEB_PERMISSION.role_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_ROLE_WEB_PERMISSION.privilige_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer priviligeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_ROLE_WEB_PERMISSION.web_info_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer webInfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_ROLE_WEB_PERMISSION.id
     *
     * @return the value of A_ROLE_WEB_PERMISSION.id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_ROLE_WEB_PERMISSION.id
     *
     * @param id the value for A_ROLE_WEB_PERMISSION.id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_ROLE_WEB_PERMISSION.role_id
     *
     * @return the value of A_ROLE_WEB_PERMISSION.role_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_ROLE_WEB_PERMISSION.role_id
     *
     * @param roleId the value for A_ROLE_WEB_PERMISSION.role_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_ROLE_WEB_PERMISSION.privilige_id
     *
     * @return the value of A_ROLE_WEB_PERMISSION.privilige_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getPriviligeId() {
        return priviligeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_ROLE_WEB_PERMISSION.privilige_id
     *
     * @param priviligeId the value for A_ROLE_WEB_PERMISSION.privilige_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setPriviligeId(Integer priviligeId) {
        this.priviligeId = priviligeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_ROLE_WEB_PERMISSION.web_info_id
     *
     * @return the value of A_ROLE_WEB_PERMISSION.web_info_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getWebInfoId() {
        return webInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_ROLE_WEB_PERMISSION.web_info_id
     *
     * @param webInfoId the value for A_ROLE_WEB_PERMISSION.web_info_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setWebInfoId(Integer webInfoId) {
        this.webInfoId = webInfoId;
    }
}