package com.amor.orm.model;

import java.util.Date;

public class ASuitMeasurement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.user_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.measure_date
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Date measureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.contract_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.consultant_uid
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer consultantUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.collar
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double collar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.wrist
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double wrist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.bust
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double bust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.shoulder_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double shoulderWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.mid_waist
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double midWaist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.waist_line
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double waistLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.sleeve
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double sleeve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.hem
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double hem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.back_length
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double backLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.front_length
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double frontLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.arm
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double arm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.forearm
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double forearm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.front_breast_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double frontBreastWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.back_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double backWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.pants_length
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double pantsLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.crotch_depth
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double crotchDepth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.leg_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double legWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.thigh
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double thigh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.lower_leg
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double lowerLeg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.height
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.weight
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.body_shape
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer bodyShape;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.stance
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer stance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.shoulder_shape
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer shoulderShape;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.abdomen_shape
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer abdomenShape;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.payment
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_SUIT_MEASUREMENT.invoice
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private String invoice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.user_id
     *
     * @return the value of A_SUIT_MEASUREMENT.user_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.user_id
     *
     * @param userId the value for A_SUIT_MEASUREMENT.user_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.measure_date
     *
     * @return the value of A_SUIT_MEASUREMENT.measure_date
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Date getMeasureDate() {
        return measureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.measure_date
     *
     * @param measureDate the value for A_SUIT_MEASUREMENT.measure_date
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setMeasureDate(Date measureDate) {
        this.measureDate = measureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.contract_id
     *
     * @return the value of A_SUIT_MEASUREMENT.contract_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.contract_id
     *
     * @param contractId the value for A_SUIT_MEASUREMENT.contract_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.consultant_uid
     *
     * @return the value of A_SUIT_MEASUREMENT.consultant_uid
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getConsultantUid() {
        return consultantUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.consultant_uid
     *
     * @param consultantUid the value for A_SUIT_MEASUREMENT.consultant_uid
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setConsultantUid(Integer consultantUid) {
        this.consultantUid = consultantUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.collar
     *
     * @return the value of A_SUIT_MEASUREMENT.collar
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getCollar() {
        return collar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.collar
     *
     * @param collar the value for A_SUIT_MEASUREMENT.collar
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setCollar(Double collar) {
        this.collar = collar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.wrist
     *
     * @return the value of A_SUIT_MEASUREMENT.wrist
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getWrist() {
        return wrist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.wrist
     *
     * @param wrist the value for A_SUIT_MEASUREMENT.wrist
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setWrist(Double wrist) {
        this.wrist = wrist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.bust
     *
     * @return the value of A_SUIT_MEASUREMENT.bust
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getBust() {
        return bust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.bust
     *
     * @param bust the value for A_SUIT_MEASUREMENT.bust
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setBust(Double bust) {
        this.bust = bust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.shoulder_width
     *
     * @return the value of A_SUIT_MEASUREMENT.shoulder_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getShoulderWidth() {
        return shoulderWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.shoulder_width
     *
     * @param shoulderWidth the value for A_SUIT_MEASUREMENT.shoulder_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setShoulderWidth(Double shoulderWidth) {
        this.shoulderWidth = shoulderWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.mid_waist
     *
     * @return the value of A_SUIT_MEASUREMENT.mid_waist
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getMidWaist() {
        return midWaist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.mid_waist
     *
     * @param midWaist the value for A_SUIT_MEASUREMENT.mid_waist
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setMidWaist(Double midWaist) {
        this.midWaist = midWaist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.waist_line
     *
     * @return the value of A_SUIT_MEASUREMENT.waist_line
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getWaistLine() {
        return waistLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.waist_line
     *
     * @param waistLine the value for A_SUIT_MEASUREMENT.waist_line
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setWaistLine(Double waistLine) {
        this.waistLine = waistLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.sleeve
     *
     * @return the value of A_SUIT_MEASUREMENT.sleeve
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getSleeve() {
        return sleeve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.sleeve
     *
     * @param sleeve the value for A_SUIT_MEASUREMENT.sleeve
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setSleeve(Double sleeve) {
        this.sleeve = sleeve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.hem
     *
     * @return the value of A_SUIT_MEASUREMENT.hem
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getHem() {
        return hem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.hem
     *
     * @param hem the value for A_SUIT_MEASUREMENT.hem
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setHem(Double hem) {
        this.hem = hem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.back_length
     *
     * @return the value of A_SUIT_MEASUREMENT.back_length
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getBackLength() {
        return backLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.back_length
     *
     * @param backLength the value for A_SUIT_MEASUREMENT.back_length
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setBackLength(Double backLength) {
        this.backLength = backLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.front_length
     *
     * @return the value of A_SUIT_MEASUREMENT.front_length
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getFrontLength() {
        return frontLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.front_length
     *
     * @param frontLength the value for A_SUIT_MEASUREMENT.front_length
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setFrontLength(Double frontLength) {
        this.frontLength = frontLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.arm
     *
     * @return the value of A_SUIT_MEASUREMENT.arm
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getArm() {
        return arm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.arm
     *
     * @param arm the value for A_SUIT_MEASUREMENT.arm
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setArm(Double arm) {
        this.arm = arm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.forearm
     *
     * @return the value of A_SUIT_MEASUREMENT.forearm
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getForearm() {
        return forearm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.forearm
     *
     * @param forearm the value for A_SUIT_MEASUREMENT.forearm
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setForearm(Double forearm) {
        this.forearm = forearm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.front_breast_width
     *
     * @return the value of A_SUIT_MEASUREMENT.front_breast_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getFrontBreastWidth() {
        return frontBreastWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.front_breast_width
     *
     * @param frontBreastWidth the value for A_SUIT_MEASUREMENT.front_breast_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setFrontBreastWidth(Double frontBreastWidth) {
        this.frontBreastWidth = frontBreastWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.back_width
     *
     * @return the value of A_SUIT_MEASUREMENT.back_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getBackWidth() {
        return backWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.back_width
     *
     * @param backWidth the value for A_SUIT_MEASUREMENT.back_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setBackWidth(Double backWidth) {
        this.backWidth = backWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.pants_length
     *
     * @return the value of A_SUIT_MEASUREMENT.pants_length
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getPantsLength() {
        return pantsLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.pants_length
     *
     * @param pantsLength the value for A_SUIT_MEASUREMENT.pants_length
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setPantsLength(Double pantsLength) {
        this.pantsLength = pantsLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.crotch_depth
     *
     * @return the value of A_SUIT_MEASUREMENT.crotch_depth
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getCrotchDepth() {
        return crotchDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.crotch_depth
     *
     * @param crotchDepth the value for A_SUIT_MEASUREMENT.crotch_depth
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setCrotchDepth(Double crotchDepth) {
        this.crotchDepth = crotchDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.leg_width
     *
     * @return the value of A_SUIT_MEASUREMENT.leg_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getLegWidth() {
        return legWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.leg_width
     *
     * @param legWidth the value for A_SUIT_MEASUREMENT.leg_width
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setLegWidth(Double legWidth) {
        this.legWidth = legWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.thigh
     *
     * @return the value of A_SUIT_MEASUREMENT.thigh
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getThigh() {
        return thigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.thigh
     *
     * @param thigh the value for A_SUIT_MEASUREMENT.thigh
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setThigh(Double thigh) {
        this.thigh = thigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.lower_leg
     *
     * @return the value of A_SUIT_MEASUREMENT.lower_leg
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getLowerLeg() {
        return lowerLeg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.lower_leg
     *
     * @param lowerLeg the value for A_SUIT_MEASUREMENT.lower_leg
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setLowerLeg(Double lowerLeg) {
        this.lowerLeg = lowerLeg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.height
     *
     * @return the value of A_SUIT_MEASUREMENT.height
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.height
     *
     * @param height the value for A_SUIT_MEASUREMENT.height
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.weight
     *
     * @return the value of A_SUIT_MEASUREMENT.weight
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.weight
     *
     * @param weight the value for A_SUIT_MEASUREMENT.weight
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.body_shape
     *
     * @return the value of A_SUIT_MEASUREMENT.body_shape
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getBodyShape() {
        return bodyShape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.body_shape
     *
     * @param bodyShape the value for A_SUIT_MEASUREMENT.body_shape
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setBodyShape(Integer bodyShape) {
        this.bodyShape = bodyShape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.stance
     *
     * @return the value of A_SUIT_MEASUREMENT.stance
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getStance() {
        return stance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.stance
     *
     * @param stance the value for A_SUIT_MEASUREMENT.stance
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setStance(Integer stance) {
        this.stance = stance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.shoulder_shape
     *
     * @return the value of A_SUIT_MEASUREMENT.shoulder_shape
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getShoulderShape() {
        return shoulderShape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.shoulder_shape
     *
     * @param shoulderShape the value for A_SUIT_MEASUREMENT.shoulder_shape
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setShoulderShape(Integer shoulderShape) {
        this.shoulderShape = shoulderShape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.abdomen_shape
     *
     * @return the value of A_SUIT_MEASUREMENT.abdomen_shape
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getAbdomenShape() {
        return abdomenShape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.abdomen_shape
     *
     * @param abdomenShape the value for A_SUIT_MEASUREMENT.abdomen_shape
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setAbdomenShape(Integer abdomenShape) {
        this.abdomenShape = abdomenShape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.payment
     *
     * @return the value of A_SUIT_MEASUREMENT.payment
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.payment
     *
     * @param payment the value for A_SUIT_MEASUREMENT.payment
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setPayment(Integer payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_SUIT_MEASUREMENT.invoice
     *
     * @return the value of A_SUIT_MEASUREMENT.invoice
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public String getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_SUIT_MEASUREMENT.invoice
     *
     * @param invoice the value for A_SUIT_MEASUREMENT.invoice
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setInvoice(String invoice) {
        this.invoice = invoice == null ? null : invoice.trim();
    }
}