package com.amor.orm.model;

public class AUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.name
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.gender
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.identity_code
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private String identityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.tel
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.email
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.store_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.username
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.password
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.status
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.login_code
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private String loginCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER.register_from
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private String registerFrom;
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.id
     *
     * @return the value of A_USER.id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.id
     *
     * @param id the value for A_USER.id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.name
     *
     * @return the value of A_USER.name
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.name
     *
     * @param name the value for A_USER.name
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.gender
     *
     * @return the value of A_USER.gender
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.gender
     *
     * @param gender the value for A_USER.gender
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.identity_code
     *
     * @return the value of A_USER.identity_code
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public String getIdentityCode() {
        return identityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.identity_code
     *
     * @param identityCode the value for A_USER.identity_code
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setIdentityCode(String identityCode) {
        this.identityCode = identityCode == null ? null : identityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.tel
     *
     * @return the value of A_USER.tel
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.tel
     *
     * @param tel the value for A_USER.tel
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.email
     *
     * @return the value of A_USER.email
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.email
     *
     * @param email the value for A_USER.email
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.store_id
     *
     * @return the value of A_USER.store_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.store_id
     *
     * @param storeId the value for A_USER.store_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.username
     *
     * @return the value of A_USER.username
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.username
     *
     * @param username the value for A_USER.username
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.password
     *
     * @return the value of A_USER.password
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.password
     *
     * @param password the value for A_USER.password
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.status
     *
     * @return the value of A_USER.status
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.status
     *
     * @param status the value for A_USER.status
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.login_code
     *
     * @return the value of A_USER.login_code
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public String getLoginCode() {
        return loginCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.login_code
     *
     * @param loginCode the value for A_USER.login_code
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setLoginCode(String loginCode) {
        this.loginCode = loginCode == null ? null : loginCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER.register_from
     *
     * @return the value of A_USER.register_from
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public String getRegisterFrom() {
        return registerFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER.register_from
     *
     * @param registerFrom the value for A_USER.register_from
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setRegisterFrom(String registerFrom) {
        this.registerFrom = registerFrom == null ? null : registerFrom.trim();
    }
}