package com.amor.orm.model;

public class AUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER_ROLE.id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER_ROLE.user_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A_USER_ROLE.role_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER_ROLE.id
     *
     * @return the value of A_USER_ROLE.id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER_ROLE.id
     *
     * @param id the value for A_USER_ROLE.id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER_ROLE.user_id
     *
     * @return the value of A_USER_ROLE.user_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER_ROLE.user_id
     *
     * @param userId the value for A_USER_ROLE.user_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A_USER_ROLE.role_id
     *
     * @return the value of A_USER_ROLE.role_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A_USER_ROLE.role_id
     *
     * @param roleId the value for A_USER_ROLE.role_id
     *
     * @mbggenerated Fri Sep 16 21:54:58 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}